version: 5.5.0.4
type: common
authorName: "Ilya I"
moduleName: "Kount"
description: "Trust and safety solutions for payment fraud, identity, and compliance."
minorRequiredCoreVersion: 0
dependsOn:
  - Iidev-CloverPayments
incompatibleWith: {}
showSettingsForm: true
canDisable: true
autoloader:
    - vendor/autoload.php
